name: identity_firebase_facebook
description: Facebook SSO by Firebase for Identity package
version: 0.2.0
author: Long Do <me@dotronglong.com>
homepage: https://github.com/dotronglong/dart-identity-firebase-facebook

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sso: ^0.2.0
  identity: ^0.2.0
  identity_firebase: ^0.2.0
  firebase_auth: ^0.15.3
  flutter_facebook_login: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/facebook.png